In [2]:
from IPython.display import HTML
HTML('<iframe src=http://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data width=300 height=300></iframe>')


In [27]:
from sklearn.datasets import load_iris
from sklearn.cross_validation import train_test_split
import numpy as np

In [4]:
iris = load_iris()


In [5]:
type(iris)

sklearn.datasets.base.Bunch

In [6]:
print (iris.data)

[[ 5.1  3.5  1.4  0.2]
 [ 4.9  3.   1.4  0.2]
 [ 4.7  3.2  1.3  0.2]
 [ 4.6  3.1  1.5  0.2]
 [ 5.   3.6  1.4  0.2]
 [ 5.4  3.9  1.7  0.4]
 [ 4.6  3.4  1.4  0.3]
 [ 5.   3.4  1.5  0.2]
 [ 4.4  2.9  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 5.4  3.7  1.5  0.2]
 [ 4.8  3.4  1.6  0.2]
 [ 4.8  3.   1.4  0.1]
 [ 4.3  3.   1.1  0.1]
 [ 5.8  4.   1.2  0.2]
 [ 5.7  4.4  1.5  0.4]
 [ 5.4  3.9  1.3  0.4]
 [ 5.1  3.5  1.4  0.3]
 [ 5.7  3.8  1.7  0.3]
 [ 5.1  3.8  1.5  0.3]
 [ 5.4  3.4  1.7  0.2]
 [ 5.1  3.7  1.5  0.4]
 [ 4.6  3.6  1.   0.2]
 [ 5.1  3.3  1.7  0.5]
 [ 4.8  3.4  1.9  0.2]
 [ 5.   3.   1.6  0.2]
 [ 5.   3.4  1.6  0.4]
 [ 5.2  3.5  1.5  0.2]
 [ 5.2  3.4  1.4  0.2]
 [ 4.7  3.2  1.6  0.2]
 [ 4.8  3.1  1.6  0.2]
 [ 5.4  3.4  1.5  0.4]
 [ 5.2  4.1  1.5  0.1]
 [ 5.5  4.2  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 5.   3.2  1.2  0.2]
 [ 5.5  3.5  1.3  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 4.4  3.   1.3  0.2]
 [ 5.1  3.4  1.5  0.2]
 [ 5.   3.5  1.3  0.3]
 [ 4.5  2.3  1.3  0.3]
 [ 4.4  3.2  1.3  0.2]
 [ 5.   3.5

In [7]:
print(iris.feature_names)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [8]:
print(iris.target)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [9]:
print(iris.target_names)

['setosa' 'versicolor' 'virginica']


In [10]:
print(type(iris.data))
print(type(iris.target))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [11]:
print(iris.data.shape)

(150, 4)


In [12]:
print(iris.target.shape)

(150,)


In [31]:
x = iris.data
y = iris.target


In [17]:
#KNN classification
#Steps: 1. Pick a value for K
#2. finds k nearest observations, predicts most common class.

In [18]:
print(x.shape)
print(y.shape)

(150, 4)
(150,)


# ML process



## KNN finds n nearest neighbors then takes average of their responses and predicts that as the value.

In [19]:
from sklearn.neighbors import KNeighborsClassifier

# 2. Instantiate(make an instance of) the estimator(model)

In [20]:
knn = KNeighborsClassifier(n_neighbors=4)

    knn an instance of model that can predict, n_neighbors a hyperparameter now means 4 nearest neighbor.

# 3. Training the model.

In [21]:
knn.fit(x,y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=4, p=2,
           weights='uniform')

# 4. Make predictions on new values

In [34]:
prediction = knn.predict([3,5,4,2])
print('Prediction is: {}'.format(iris.target_names[prediction][0]))

Prediction is: versicolor


C:\Users\Ankitom\AppData\Local\Continuum\Anaconda3\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


In [36]:
x_new = [[3,5,4,2],[5,4,3,2]]
pred = knn.predict(x_new)

print('Prediction is: {}  {}'.format(iris.target_names[pred][0], iris.target_names[pred][1]))


Prediction is: versicolor  versicolor


# Using a different n neighbors value


In [38]:
knn = KNeighborsClassifier(n_neighbors=9)
knn.fit(x, y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=9, p=2,
           weights='uniform')

In [40]:
prediction = knn.predict([3,5,4,2])
print('Prediction is: {}'.format(iris.target_names[prediction][0]))

Prediction is: versicolor


C:\Users\Ankitom\AppData\Local\Continuum\Anaconda3\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


 # Using a different classification method


In [42]:
# Import the class
from sklearn.linear_model import LogisticRegression

# Instantiate the models(using default parameters))
logreg = LogisticRegression()

# Fit the model
logreg.fit(x,y)

# Predict using the model

pred =logreg.predict(x_new)

print('Prediction is: {}  {}'.format(iris.target_names[pred][0], iris.target_names[pred][1]))

Prediction is: virginica  setosa
